version: '3.9'

services:
  # -------------------------
  # BACKEND
  # -------------------------
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: payment-api`
    env_file:
      - .env
    depends_on:
      - postgres
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.payment-api.rule=Host(`api.energy-cerber.ru`)"
      - "traefik.http.routers.payment-api.entrypoints=websecure"
      - "traefik.http.routers.payment-api.tls.certresolver=letsencrypt"
      - "traefik.http.services.payment-api.loadbalancer.server.port=8000"
    networks:
      - my_network
    ports:
      - "8000:8000"

  # -------------------------
  # POSTGRES
  # -------------------------
  postgres:
    container_name: payment-db
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5434:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - my_network

volumes:
  pgdata:


networks:
  my_network:
    external: true
    name: vps-network
