version: '3.9'

services:
  api:
    build: .
    container_name: payment-api
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "8000:8000"

  postgres:
    container_name: payment-db
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    volumes:
      - ./pgdata:/var/lib/postgresql/data
