"""Create operations table

Revision ID: ff9678690015
Revises: 1bb2c1123fd7
Create Date: 2025-04-28 10:13:50.612983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff9678690015'
down_revision: Union[str, None] = '1bb2c1123fd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oparations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('user', 'group', 'semester', 'payment', name='operationtypes'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('oparations')
    # ### end Alembic commands ###
